### ISSUE TITLE
build_charms_with_cache.yaml: Build breaks after documentation file is added

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/data-platform-workflows#14]
`Parts processing error: Failed to copy '/root/parts/charm/src/docs/documentation_landing.md': no such file or directory.`

https://github.com/canonical/mysql-k8s-operator/actions/runs/4227846811

**Comment by taurus-forever** [comment]
For the history, It looks like cache might have two files/caches with the same name... somehow...
