### ISSUE TITLE
Pipeline live debugging enabled as before (tmate)

### ISSUE THREAD

**Issue by juditnovak** [canonical/data-platform-workflows#165]
With the old workflows it was very easy to debug worse issues with one's application (only appearing on the pipelines ;-) ) using [Tmate](https://github.com/mxschmitt/action-tmate).

However it's less convenient to do with the latest versions of the workflows.

Would it be possible to re-introduce this, truly important feature?

**Comment by taurus-forever** [comment]
@carlcsaposs-canonical  do not expect Azure runners the nearest time. The topic is outside of our control.

AFAIK, SSH access is possible nowadays for self-hosted runners. Can we use this approach?
What about to add optional [upterm](https://discourse.charmhub.io/t/charming-debug-on-github/9295)? It can be similar to the optional `allure: true`.

What do you think?

**Comment by juditnovak** [comment]
Enabled now internally for Canonical users. See [MM discussion] (https://chat.canonical.com/canonical/pl/q6eay419itbu8n6xga7z78hqko)
