### ISSUE TITLE
Timeout on jhack tail (integration_test_charm.yaml)

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/data-platform-workflows#223]
jhack tail takes longer than 3 minutes when debug log is large
e.g. https://github.com/canonical/mongodb-operator/actions/runs/10276480008/job/28437246655#step:33:1

not exactly sure what's the root cause, it appears to be related to log size but not only that

the previously linked run has 74.8 MB debug log

this run has two models each with a 4.0 MB log: https://github.com/canonical/postgresql-operator/actions/runs/10276476581/job/28437198646 (jhack tail takes 1:19)

this run has a 13.6 MB log: https://github.com/canonical/mongodb-operator/actions/runs/10276480008/job/28437244101#step:33:7 (jhack tail takes >3 min)

reported by @taurus-forever

**Comment by taurus-forever** [comment]
Thank you @carlcsaposs-canonical , we can report it officially to jhack repo if necessary. cc: @PietroPasotti
